### ISSUE TITLE
Tenant applied on request that shouldn't with joins in request

### ISSUE THREAD

**Issue by herbertia** [ErwinM/acts_as_tenant#101]
Hi,

We have a project ruby 2.0.0 rails 4.0.0 using acts_as_tenant 0.3.1. I am upgrading to ruby 2.1.2p95, rails 4.1.9 and acts_as_tenant 0.3.8.
When I am trying in rails console to do a joins request I have an error of tenant not set.
So I have created 3 little projects:
 - r400_tenant: with ruby 2.0.0-p247, rails 4.0.0 and acts_as_tenant 0.3.8 and in the rails console I can do my request without problem.
https://gist.github.com/herbertia/91a3dde06d430a203e63
 - r419: with ruby 2.1.2-p95, rails 4.1.9 without acts_as_tenant and in the rails console I can do my request without problem.
https://gist.github.com/herbertia/d543da940066b4031764
 - 419_tenant: with ruby 2.1.2-p95, rails 4.1.9 and acts_as_tenant 0.3.8 and in the rails console the same request goes in error with tenant not set.
https://gist.github.com/herbertia/8e1d6d5123bc589a0ce6

I did 3 gists with the simple models, migration, seeds, request in console and result in order for you to check.
Could you have a look and let me know if I did something wrong or if there is a bug in the gem?

Thanks in advance for your help.

Sincerely,
Stephanie

**Comment by ErwinM** [comment]
Hi Stephanie,

The issue you are running into is caused by changes to how `default_scope` is handled in the query builder of active_record. In 4.1.9 query builder now, correctly imo, evaluates the default_scope of relations. 

This behavior does however trigger AaT's check for a valid tenant. Since you are using `require_tenant = true` as a configuration option, it will only allow the join on a scoped model with a valid tenant set.

In 4.0.0 query builder did evaluate the default_scope of associations (or not consistently anyway). If you dig through the active_record issues you will see a lot of discussions around this topic around 4.0.0.

Make sense?

**Comment by herbertia** [comment]
Hi Erwin,

Thank you for your answer.
Yes I thought it was due to the default_scope.
The only thing is if we change the config require_tenant = true to false, yes the join request will work but we don't have anymore the security of making sure that all requests are scoped.
I know my remark doesn't make any sense said like that but as our Customer model is the tenant it is also interesting to make requests for all of them.
Anyway thank you for your answer and will see what we can do now.

Sincerely,
Stephanie
