### ISSUE TITLE
Setting `require_tenant` to true in initializer causes migrations to fail with ActsAsTenant::NoTenant

### ISSUE THREAD

**Issue by PandaWhisperer** [ErwinM/acts_as_tenant#122]
As per title. Initializers are executed when migrations are run, so setting `require_tenant` to true in `config/initializers/acts_as_tenant.rb` causes all following migrations to fail.

**Comment by ErwinM** [comment]
Could you share some code/example app where this happens. In my test apps migrations run fine with `require_tenant` set to `true`.

**Comment by lleolin** [comment]
I was having this problem. An older migration was using `Model.all` for a model that acts_as_tenant. This is problematic because the migration for the tenants table doesn't run until after this migration, so it isn't even possible at that stage to even grab a Tenant if I wanted to.

Not sure if this a bug per se, and I'm not sure if it's even considered good practice to update records through the model in a migration. Either way `Model.unscoped` seems to get around acts_as_tenant.
