### ISSUE TITLE
Adding an except class name to the require_tenant configuration (Suggestion & already done on my repo)

### ISSUE THREAD

**Issue by hgcode** [ErwinM/acts_as_tenant#123]
Hi Erwin, in my setup, all my models have a Company as the "tenant account", that way I can have everything available not only to an account but to everybody that belongs to that company. 

I think the require_tenant is a nice enforcer, however it throws an exception for the User model when using Devise, so I made a patch that allows you to specify an exception at init time for the User model.. 

https://github.com/hgcode/acts_as_tenant/commit/af684f92f3d5137602aff15ec51ced815855eaeb

It works for my case, just putting it here in case you want to take a look at it. 

ActsAsTenant.configure do |config|
  config.require_tenant = true
  config.require_tenant_except = ["User"]
end

I'm enforcing that the User belongs to a company somewhere else in my code..

Thanks for your work

**Comment by TechRsch** [comment]
@hgcode  I like this and could use it.  Did you request a pull?

**Comment by ErwinM** [comment]
#131 now allows you to achieve the same with a slightly different implementation

**Comment by TechRsch** [comment]
Love your code!  However, this solution differs substantially from the other.  The other one covers a block of code and this one covers specific models.  I have code that accesses multiple models, of course, but some models should have tenants and others should not.  For example, a company owns a car, and the company is the tenant.  That car is a specific year, make, model, color, etc.  Those tables are shared and should not have tenants.  However, a block of code then accesses both tenanted models and non-tenanted models.  Is it possible to implement this solution?

**Comment by ErwinM** [comment]
Couldn't you just not include acts_as_tenant in the models you want shared?                                                                                                                                                                                                                                                                                                                                        Erwin                                                                                                                                                                                                                From: Richard RodgersSent: Saturday, 19 March 2016 17:01To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantCc: ErwinMSubject: Re: [acts_as_tenant] Adding an except class name to the require_tenant configuration (Suggestion & already done on my repo) (#123)Love your code!  However, this solution differs substantially from the other.  The other one covers a block of code and this one covers specific models.  I have code that accesses multiple models, of course, but some models should have tenants and others should not.  For example, a company owns a car, and the company is the tenant.  That car is a specific year, make, model, color, etc.  Those tables are shared and should not have tenants.  However, a block of code then accesses both tenanted models and non-tenanted models.  Is it possible to implement this solution?

—You are receiving this because you modified the open/close state.Reply to this email directly or view it on GitHub
