### ISSUE TITLE
acts_as_tenant for non sub-domain

### ISSUE THREAD

**Issue by idlogi** [ErwinM/acts_as_tenant#138]
Hi, can use this gem for non sub-domain use ? I don't wanna manage subdomain with this just 1 single domain for all account of saas. Is it possible ? Thanks

**Comment by ErwinM** [comment]
Can you describe how you would like to use it instead?                                                                                                                                                                                                                                                                                                                                        Erwin                                                                                                                                                                                                                From: Idlogi WorksSent: Tuesday, 3 May 2016 01:32To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantSubject: [ErwinM/acts_as_tenant] acts_as_tenant for non sub-domain (#138)Hi, can use this gem for non sub-domain use ? I don't wanna manage subdomain with this just 1 single domain for all account of saas. Is it possible ? Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by hamdisy** [comment]
Hi  Erwin !
Ex. www.domain.com is a Saas Domain.
When each tenant register on web site, we don't want maintain each subdomain for each tenant.
So, After a user logs on to a web, no need to redirect to subdomain still stick to www.domain.com, but system can identify this user is belongs to certain scheme (ex. if we use postgresql).
Hopefully you got my point.

Thanks Erwin!

**Comment by ErwinM** [comment]
This can be done by using a filter in your `application_controller` like described in the readme. It's under the heading: 'Setting the current tenant in a controller, manually'
