### ISSUE TITLE
Rubygems version is very out of date

### ISSUE THREAD

**Issue by Tongboy** [ErwinM/acts_as_tenant#144]
Any plans to resume tagging and updating ruby gems?

I just today realized the rubygems version hasn't been updated since mid 2015.

Thank you!

**Comment by alexperto** [comment]
is there any I can help to make this happen @ErwinM ?

**Comment by tparsnick** [comment]
We would like to use the "without tenant" feature in master in an official capacity.  @ErwinM will you be releasing it soon with a new version tag?  We are including this feature in our gemfile by explicitly naming the commit, but it feels hacky.  Thanks so much.

**Comment by ErwinM** [comment]
‎@tparsnick I will have a look and release a new version next week. At the moment I am on a sailing boat ;)                                                                                                                                                                                                                                                                                                                                        Erwin                                                                                                                                                                                                                From: tparsnickSent: Thursday, 4 August 2016 18:44To: ErwinM/acts_as_tenantReply To: ErwinM/acts_as_tenantCc: ErwinM; MentionSubject: Re: [ErwinM/acts_as_tenant] Rubygems version is very out of date (#144)We would like to use the "without tenant" feature in master in an official capacity.  @ErwinM will you be releasing it soon with a new version tag?  We are including this feature in our gemfile by explicitly naming the commit, but it feels hacky.  Thanks so much.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ErwinM/acts_as_tenant","title":"ErwinM/acts_as_tenant","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ErwinM/acts_as_tenant"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tparsnick in #144: We would like to use the \"without tenant\" feature in master in an official capacity.  @ErwinM will you be releasing it soon with a new version tag?  We are including this feature in our gemfile by explicitly naming the commit, but it feels hacky.  Thanks so much."}],"action":{"name":"View Issue","url":"https://github.com/ErwinM/acts_as_tenant/issues/144#issuecomment-237611774"}}}

**Comment by ErwinM** [comment]
@alexperto @Tongboy @tparsnick Master branch is now released as version 0.4.0.
