### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by elTincho90** [ErwinM/acts_as_tenant#147]
Any plans for a new release ? 

We are missing the `ActsAsTenant#without_tenant` feature :(

**Comment by ErwinM** [comment]
Will release tomorrow                                                                                                                                                                         Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                                                                   From:notifications@github.comSent:12 August 2016 11:03 p.m.To:acts_as_tenant@noreply.github.comReply to:reply@reply.github.comSubject:[ErwinM/acts_as_tenant] New release ? (#147)  Any plans for a new release ? 

We are missing the ActsAsTenant#without_tenant feature :(

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ErwinM** [comment]
@elTincho90 done.
