### ISSUE TITLE
scope models by default

### ISSUE THREAD

**Issue by veeral-patel** [ErwinM/acts_as_tenant#221]
Hi - is there any way to add `acts_as_tenant` to all models by default?

**Comment by veeral-patel** [comment]
Update - you can try adding `acts_as_tenant` to `application_record.rb`

I need to somehow exclude my tenant model, though

**Comment by excid3** [comment]
You can add `acts_as_tenant` to ApplicationRecord and make sure all your models inherit from that (which they do in recent versions of Rails).

```
class ApplicationRecord < ActiveRecord::Base
  acts_as_tenant :account
end
```

**Comment by veeral-patel** [comment]
@excid3 Hey! Thank you! I have one model (`Tenant`) which I don't want to add `acts_as_tenant` to. Any idea how to achieve this?

**Comment by excid3** [comment]
Easy solution would be to have that model inherit from ActiveRecord::Base instead of ApplicationRecord. 

Or create another subclass for TenantRecord and have all your models inherit from that like the ApplicationRecord is used for. That would preserve ApplicationRecord so you can use it for anything that spans all models including Tenant, but you may not need that. Plus it requires manually updating all models to inherit from the right place, so I'd do the first option unless I needed ApplicationRecord for something else.

Either way would work just fine.

**Comment by veeral-patel** [comment]
@excid3 Thank you! So I read a couple posts online on this subject and it seems like `ApplicationRecord` is basically just `ActiveRecord::Base`, but since it's a regular class in your codebase, you can add code to it like you would any other class.

So I think my application wouldn't be affected by inheriting from `ActiveRecord::Base` instead of `ApplicationRecord`, considering my ApplicationRecord class is empty. Let me know if I'm wrong @excid3 

I'm going to try out the first approach and I'll report back if I run into any problems.

**Comment by veeral-patel** [comment]
It worked! Thanks @excid3!
